// Generated by SugarLisp v0.5
var csp = require("js-csp");
var chan = csp.chan;
var timeout = csp.timeout;
var alts = csp.alts;

var x = (yield csp.take(3));

var val = undefined,
  ch = undefined;
val = (yield csp.take(ch));