rm macros.js.sav
rm keywords.js.sav
rm test/sugar/simpleGo.js.sav
rm test/sugar/simpleGo2.js.sav
rm test/sugar/testCSP.js.sav
rm test/slisp/goxlispy.js.sav
rm test/slisp/goxlispy2.js.sav
rm examples/js-csp-project/boring.fan-in-using-select.js.sav
rm examples/js-csp-project/boring.fan-in.js.sav
rm examples/js-csp-project/boring.service.js.sav
rm examples/js-csp-project/boring.simple.js.sav
rm examples/js-csp-project/boring.js.sav
rm examples/js-csp-project/boring.timeout-using-select.js.sav
rm examples/js-csp-project/boring.timeout-whole-conversation-using-select.js.sav
rm examples/js-csp-project/daisy-chain.js.sav
rm examples/js-csp-project/fake-search-3.0.js.sav
rm examples/js-csp-project/pingpong-tadpoles.js.sav
rm examples/js-csp-project/pingpong.js.sav
rm examples/taming-csp/sugar/0-csp-intro-a.js.sav
rm examples/taming-csp/sugar/0-csp-intro-b.js.sav
rm examples/taming-csp/sugar/1-basic-principles-a.js.sav
rm examples/taming-csp/sugar/1-basic-principles-b.js.sav
rm examples/taming-csp/sugar/1-basic-principles-c.js.sav
rm examples/taming-csp/sugar/tadpoles/0-csp-intro-a.js.sav
rm examples/taming-csp/sugar/tadpoles/0-csp-intro-b.js.sav
rm examples/taming-csp/sugar/tadpoles/1-basic-principles-a.js.sav
rm examples/taming-csp/sugar/tadpoles/1-basic-principles-b.js.sav
rm examples/taming-csp/sugar/tadpoles/1-basic-principles-c.js.sav
rm examples/tardisgo/nonblock.js.sav
rm examples/taming-csp/slisp/0-csp-intro-a.js.sav
