set -x
diff -b macros.js macros.js.sav
diff -b gentab.js gentab.js.sav
diff -b test/sugar/simpleGo.js test/sugar/simpleGo.js.sav
diff -b test/sugar/simpleGo2.js test/sugar/simpleGo2.js.sav
diff -b test/sugar/testCSP.js test/sugar/testCSP.js.sav
diff -b test/slisp/goxlispy.js test/slisp/goxlispy.js.sav
diff -b test/slisp/goxlispy2.js test/slisp/goxlispy2.js.sav
diff -b examples/js-csp-project/boring.fan-in-using-select.js examples/js-csp-project/boring.fan-in-using-select.js.sav
diff -b examples/js-csp-project/boring.fan-in.js examples/js-csp-project/boring.fan-in.js.sav
diff -b examples/js-csp-project/boring.service.js examples/js-csp-project/boring.service.js.sav
diff -b examples/js-csp-project/boring.simple.js examples/js-csp-project/boring.simple.js.sav
diff -b examples/js-csp-project/boring.js examples/js-csp-project/boring.js.sav
diff -b examples/js-csp-project/boring.timeout-using-select.js examples/js-csp-project/boring.timeout-using-select.js.sav
diff -b examples/js-csp-project/boring.timeout-whole-conversation-using-select.js examples/js-csp-project/boring.timeout-whole-conversation-using-select.js.sav
diff -b examples/js-csp-project/daisy-chain.js examples/js-csp-project/daisy-chain.js.sav
diff -b examples/js-csp-project/fake-search-3.0.js examples/js-csp-project/fake-search-3.0.js.sav
diff -b examples/js-csp-project/pingpong-tadpoles.js examples/js-csp-project/pingpong-tadpoles.js.sav
diff -b examples/js-csp-project/pingpong.js examples/js-csp-project/pingpong.js.sav
diff -b examples/taming-csp/sugar/0-csp-intro-a.js examples/taming-csp/sugar/0-csp-intro-a.js.sav
diff -b examples/taming-csp/sugar/0-csp-intro-b.js examples/taming-csp/sugar/0-csp-intro-b.js.sav
diff -b examples/taming-csp/sugar/1-basic-principles-a.js examples/taming-csp/sugar/1-basic-principles-a.js.sav
diff -b examples/taming-csp/sugar/1-basic-principles-b.js examples/taming-csp/sugar/1-basic-principles-b.js.sav
diff -b examples/taming-csp/sugar/1-basic-principles-c.js examples/taming-csp/sugar/1-basic-principles-c.js.sav
diff -b examples/taming-csp/sugar/tadpoles/0-csp-intro-a.js examples/taming-csp/sugar/tadpoles/0-csp-intro-a.js.sav
diff -b examples/taming-csp/sugar/tadpoles/0-csp-intro-b.js examples/taming-csp/sugar/tadpoles/0-csp-intro-b.js.sav
diff -b examples/taming-csp/sugar/tadpoles/1-basic-principles-a.js examples/taming-csp/sugar/tadpoles/1-basic-principles-a.js.sav
diff -b examples/taming-csp/sugar/tadpoles/1-basic-principles-b.js examples/taming-csp/sugar/tadpoles/1-basic-principles-b.js.sav
diff -b examples/taming-csp/sugar/tadpoles/1-basic-principles-c.js examples/taming-csp/sugar/tadpoles/1-basic-principles-c.js.sav
diff -b examples/tardisgo/nonblock.js examples/tardisgo/nonblock.js.sav
diff -b examples/taming-csp/slisp/0-csp-intro-a.js examples/taming-csp/slisp/0-csp-intro-a.js.sav
