// Generated by SugarLisp v0.6.5
exports["chtake"] = function(forms) {
  var macrodef = ["macro", ["channel"],
    ["yield", [
      [".", "csp", "take"],
      ["~", "channel"]
    ]]
  ];
  return this.macroexpand(forms, macrodef);
};
exports["chput"] = function(forms) {
  var macrodef = ["macro", ["channel", "value"],
    ["yield", [
      [".", "csp", "put"],
      ["~", "channel"],
      ["~", "value"]
    ]]
  ];
  return this.macroexpand(forms, macrodef);
};
exports["~>"] = function(forms) {
  var macrodef = ["macro", ["value", "channel"],
    ["yield", [
      [".", "csp", "put"],
      ["~", "channel"],
      ["~", "value"]
    ]]
  ];
  return this.macroexpand(forms, macrodef);
};
exports["<-alts"] = function(forms) {
  var macrodef = ["macro", ["...rest"],
    ["yield", [
      [".", "csp", "alts"],
      ["~", "rest"]
    ]]
  ];
  return this.macroexpand(forms, macrodef);
};
exports["<~alts"] = function(forms) {
  var macrodef = ["macro", ["...rest"],
    ["yield", [
      [".", "csp", "alts"],
      ["~", "rest"]
    ]]
  ];
  return this.macroexpand(forms, macrodef);
};