// Generated by SugarLisp v0.5
var csp = require("js-csp");
var chan = csp.chan;
var timeout = csp.timeout;
var alts = csp.alts;

var boring = require("./boring");

csp.go(function*() {
  var b = boring("boring!");
  for (var i = 0;
    (i < 5); i++) {
    console.log(("You say: " + (yield csp.take(b))));
  };
  console.log("You are boring; I'm leaving.");

});