// Generated by SugarLisp v0.6.5
var csp = require("js-csp");
var chan = csp.chan;
var timeout = csp.timeout;
var alts = csp.alts;
module.exports = function boring(message) {
  var ch = chan();
  csp.go(function*() {
    for (var i = 0; true; i++) {
      yield csp.put(ch, ["message ", i].join(''));
      (yield csp.take(timeout((Math.random() * 1000))));
    };

  });
  return ch;
}