// Generated by SugarLisp v0.6.0
var csp = require("js-csp");
var chan = csp.chan;
var timeout = csp.timeout;
var alts = csp.alts;

csp.go(function*() {
  var messages = chan();
  var signals = chan();
  var selected = yield csp.alts([
    messages
  ], {
    default: true
  });
  switch (selected.channel) {
    case messages:
      console.log("received message", selected.value);
      break;
    default:
      console.log("no message received");
      break;
  };
  var msg = "hi";
  selected = yield csp.alts([
    [
      messages,
      msg
    ]
  ], {
    default: true
  });
  switch (selected.channel) {
    case messages:
      console.log("sent message", msg);
      break;
    default:
      console.log("no message sent");
      break;
  };
  selected = yield csp.alts([
    messages,
    signals
  ], {
    default: true
  });
  switch (selected.channel) {
    case messages:
      console.log("received message", selected.value);
      break;
    case signals:
      console.log("received signal", selected.value);
      break;
    default:
      console.log("no activity");
      break;
  };

});